song_library/routes.py
import functools
import uuid
import re
import datetime
from dataclasses import asdict

from flask import (
    Blueprint,
    current_app,
    flash,
    redirect,
    render_template,
    session,
    url_for,
    request,
)
from song_library.forms import LoginForm, RegisterForm, SongForm, ExtendedSongForm
from song_library.models import User, Song
from passlib.hash import pbkdf2_sha256


pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)

def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))

        return route(*args, **kwargs)

    return route_wrapper


def datetime_formatting(song):

    time_ago = datetime.datetime.today() - song.date_added
    time_ago = time_ago.__str__()

    if time_ago.find("days") != -1 or time_ago.find("day") != -1:
        time_ago = time_ago[:(time_ago.find(","))]
        time_ago += ' ago'

    elif re.match("0:..:..", time_ago):
        time_ago = int(time_ago.split(':')[1])
        if time_ago >= 30 and time_ago <= 40:
            time_ago = "Half hour ago"
        elif time_ago >= 40:
            time_ago = "Almost an hour ago"
        else:
            time_ago = "Few minutes ago"

    else:
        time_ago = int(time_ago.split(':')[0])
        if time_ago == 1:
            time_ago = str(time_ago) + ' hour ago'
        else:
            time_ago = str(time_ago) + ' hours ago'

    return time_ago

    
@pages.route("/")
@login_required
def index():
    user_data = current_app.db.user.find_one({"email": session["email"]})
    if not user_data:
        return redirect(url_for(".logout"))

    user = User(**user_data)
    song_data = current_app.db.song.find({"_id": {"$in": user.songs}})
    songs = [Song(**song) for song in song_data]

    return render_template(
        "index.html",
        title="Songs Playlist",
        songs_data=songs,
        datetime_formatting=datetime_formatting
    )


@pages.route("/register", methods=["POST", "GET"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))
    
    form = RegisterForm()
    if form.validate_on_submit():
        user = User(
            _id=uuid.uuid4().hex, 
            email=form.email.data, 
            password=pbkdf2_sha256.hash(form.password.data), 
        )                                                     

        current_app.db.user.insert_one(asdict(user))

        flash("User registered successfully", "success")
        return redirect(url_for(".login"))

    return render_template(
        "register.html", title="Songs Playlist - Register", form=form
    )


@pages.route("/login", methods=["GET", "POST"])
def login():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()
    if form.validate_on_submit():
        
        user_data = current_app.db.user.find_one({"email": form.email.data})

        if not user_data:
            flash("Login credentials not correct", category="danger")
            return redirect(url_for(".login"))

        user = User(**user_data)
        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            session["user_id"] = user._id
            session["email"] = user.email

            return redirect(url_for(".index"))

        flash("Login credentials not correct", category="danger")
        
    return render_template("login.html", title="Songs Playlist - Login", form=form)


@pages.route("/logout")
def logout():
    del session["email"]
    del session["user_id"]

    return redirect(url_for(".login"))


@pages.route("/add", methods=["GET", "POST"])
@login_required
def add_song():
    form = SongForm()
    
    if form.validate_on_submit():
        song = Song(
            _id=uuid.uuid4().hex,
            title=form.title.data,
            band=form.band.data,
            album=form.album.data,
            date_added=datetime.datetime.today()
        )

        current_app.db.song.insert_one(asdict(song))
        current_app.db.user.update_one(
            {"_id": session["user_id"]}, {"$push": {"songs": song._id}}
        )

        return redirect(url_for(".song", _id=song._id))
    return render_template(
        "new_song.html", title="Songs Playlist - Add Song", form=form
    )


@pages.get("/song/<string:_id>")
def song(_id: str):
    
    song = Song(**current_app.db.song.find_one({"_id": _id}))
    return render_template("song_details.html", song=song)


@pages.route("/edit/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_song(_id: str):
    song = Song(**current_app.db.song.find_one({"_id": _id}))
    form = ExtendedSongForm(obj=song) 

    if form.validate_on_submit():
        song.title = form.title.data
        song.band = form.band.data
        song.album = form.album.data
        song.year = form.year.data
        song.tags = form.tags.data
        song.description = form.description.data
        song.video_link = form.video_link.data

        current_app.db.song.update_one({"_id": song._id}, {"$set": asdict(song)})
        return redirect(url_for(".song", _id=song._id))
    return render_template("song_form.html", song=song, form=form)


@pages.get("/song/<string:_id>/play")
@login_required
def play_today(_id):
    
    current_app.db.song.update_one(
        {"_id": _id}, {"$set": {"last_played": datetime.datetime.today()}}
    )

    return redirect(url_for(".song", _id=_id))


@pages.get("/song/<string:_id>/rate")
@login_required
def rate_song(_id):
    
    rating = int(request.args.get("rating"))
    current_app.db.song.update_one({"_id": _id}, {"$set": {"rating": rating}})

    return redirect(url_for(".song", _id=_id))


@pages.get("/toggle-theme")
def toggle_theme():
    current_theme = session.get("theme")

    if current_theme == "dark":
        session["theme"] = "light"
    else:
        session["theme"] = "dark"

    return redirect(request.args.get("current_page"))

song_library/templates/index.html
<!DOCTYPE html>
{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/songs.css') }}" />
{% endblock %}

{% block main_content %}

    {%- if songs_data %}
        <table class="table">
            <colgroup>
                <col style="width: 40%">
                <col style="width: 22.5%">
                <col style="width: 22.5%">
                <col style="width: 15%">
            </colgroup>
            <thead>
                <tr class="table__header">
                    <th class="table__cell table__cell--header">Title</th>
                    <th class="table__cell table__cell--header">Album</th>
                    <th class="table__cell table__cell--header">Date Added</th>
                    <th class="table__cell table__cell--header"></th>
                </tr>
            </thead>
            <tbody>
                {% for song in songs_data %}
                    <tr>
                        <td class="table__cell">
                            <p class="table__songTitle">{{ song.title }}</p>
                            <p class="table__songBand"> By {{ song.band }} </p>
                        </td>
                        <td class="table__cell table__cell--light-text">{{ song.album }}</td>
                        {% if song.date_added %}
                        <td class="table__cell table__cell--light-text">{{ datetime_formatting(song) }}</td>
                        {% else %}
                        <td class="table__cell"></td>
                        {% endif %}
                        <td class="table__cell">
                            <a href="{{ url_for('pages.song', _id=song._id) }}" class="table__link">
                                View
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
    {% else %}
        <p class="table__empty">
            You haven't added any songs yet.
            <a href="{{ url_for('pages.add_song') }}" class="link">Add one!</a>
        </p>
    {% endif %}

    <a href="{{ url_for('pages.add_song') }}" class="button button--add">
        <span>+</span>
    </a>

{% endblock %}

song_library/templates/login.html
<!DOCTYPE html>
{% from "macros/fields.jinja2" import render_text_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %} 

{% block main_content %}

    <form name="login" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}

        <div class="form__container">
            {{ form.hidden_tag() }}
    
            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
    
            <span class="form__small">
                Don't have an account? <a href="{{ url_for('pages.register') }}" class="form__link">Register here</a>.
            </span>
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

song_library/templates/register.html
<!DOCTYPE html>
{% from "macros/fields.jinja2" import render_text_field %}

{% extends "layout.html" %} 

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %} 

{% block main_content %}

    <form name="register" method="post" novalidate class="form">
        <div class="form__container">
            {{ form.hidden_tag() }}

            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
            {{ render_text_field(form.confirm_password) }}
    
            <span class="form__small">
                Already have an account? <a href="{{ url_for('pages.login') }}" class="form__link">Log in here</a>.
            </span>
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

song_library/templates/song_details.html
<!DOCTYPE html>

{% from "macros/svgs.jinja2" import star, pencil %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/song_details.css') }}" />
{% endblock %}

{% block main_content %}
<div class="container">
    <header class="song__header">
        <div class="header__row">
            <div class="song__name">
                <h1>{{ song.title }}</h1>
                <div class="song__rating"> 
                    {% for i in range(5) %} 
                    {% set order = ((5 - i) | string) %}
                        <a class="rating__link star--filled {{ 'rating__link' + order }} {{ (' star--notfilled ' if song.rating < (5 - i) else '') }}" href="{{ url_for('pages.rate_song', _id=song._id, rating=5-i) }}">
                            {{ star("star") }}
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="song__played">
                {% if song.last_played %}
                    <p>
                        Last played: <a href="{{ url_for('pages.play_today', _id=song._id) }}" class="played__link">
                            <time datetime="{{ song.last_played }}">{{song.last_played.strftime("%d %b %Y")}}</time>
                        </a>
                    </p>
                {% else %}
                    <p><a href="{{ url_for('pages.play_today', _id=song._id) }}" class="played__link">Not played yet</a></p>
                {% endif %}
                <a class="song__edit" href="{{ url_for('pages.edit_song', _id=song._id) }}">Edit {{ pencil("pencil") }}</a>
            </div>
        </div>
        <div class="header__row">
            <ul class="song__tags">
            {% for tag in song.tags %}
                <li class="song__tag">{{ tag }}</li>
            {% endfor %}
            </ul>
        </div>
    </header>
    {% if song.video_link %}
    <iframe
        class="song__video"
        src="{{ song.video_link }}"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
    </iframe>
    {% endif %}

    {% if song.description %}
        <p class="song__description">{{ song.description }}</p>
    {% else %}
        <p class="song__description">No description yet. <a class="link" href="{{ url_for('pages.edit_song', _id=song._id) }}">Add one?</a></p>
    {% endif %}
    
</div>
{% endblock %}